"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Fabricante = void 0;
var Fabricante;
(function (Fabricante) {
    Fabricante["Desconhecido"] = "Desconhecido";
    Fabricante["GeneralMotors"] = "General Motors";
    Fabricante["Fiat"] = "Fiat";
    Fabricante["Volkswagen"] = "Volkswagen";
    Fabricante["Volvo"] = "Volvo";
    Fabricante["Volare"] = "Volare";
    Fabricante["MarcoPolo"] = "Marco Polo";
    Fabricante["Neobus"] = "Neobus";
    Fabricante["Monark"] = "Monark";
    Fabricante["Caloi"] = "Caloi";
    Fabricante["Fibrafort"] = "Fibrafort";
    Fabricante["ProBoat"] = "Pro Boat";
    Fabricante["Honda"] = "Honda";
    Fabricante["BMW"] = "BMW";
    Fabricante["Ducati"] = "Ducati";
    Fabricante["Kawasaki"] = "Kawasaki";
    Fabricante["HarleyDavidson"] = "Harley Davidson";
})(Fabricante = exports.Fabricante || (exports.Fabricante = {}));
